# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
